name: Web Build + Deployment to GitHub Pages 

on:
  # Runs on push to any of the below branches
  push:
    branches:
      - main

  # Runs on pull request events that target one of the below branches
  pull_request:
    branches:
      - main

  # Allows manual workflow runs
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  # https://flet.dev/docs/publish#versioning
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0

  # Python version to use
  PYTHON_VERSION: 3.12.8

  # flet-cli version to install
  FLET_CLI_VERSION: 0.27.5

  # UTF-8 encoding
  PYTHONUTF8: 1

  # Disable rich output in Flet CLI
  FLET_CLI_NO_RICH_OUTPUT: 1

  # Disable progress bars when using UV
  UV_NO_PROGRESS: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4  # Upgraded from v2 to v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install flet-cli ${{ env.FLET_CLI_VERSION }}
      run: |
        python -m pip install --upgrade pip
        pip install flet-cli==$FLET_CLI_VERSION

    - name: Verify Project Structure
      run: |
        echo "Checking project files..."
        ls -la

    - name: Flet Build Web
      run: |
        echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}, USER: ${GITHUB_REPOSITORY%/*}, PROJECT_BASE_URL: ${GITHUB_REPOSITORY#*/}"
        flet build web --module-name --base-url ${GITHUB_REPOSITORY#*/} --route-url-strategy hash  # Fixed spacing issue

    - name: Validate Build Output
      run: |
        if [ -d "build/web" ]; then
          echo "✅ Build directory found!"
        else
          echo "❌ ERROR: Build directory not found!"
          exit 1
        fi

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: web-build-artifact
        path: build/web

  deploy:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'  
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
